### ISSUE TITLE
Fit patch size distributions

### ISSUE THREAD

**Issue by alaindanet** [fdschneider/spatial_warnings#15] opened 2015-07-06 12:18 UTC
[fitpsd.R](https://github.com/fdschneider/spatial_warnings/blob/master/R/fitpsd.R) et  [patchsizedistr_ews.R](https://github.com/fdschneider/spatial_warnings/blob/master/R/patchsizedistr_ews.R)

patchsizedistr_ews.R seems to be obsolete.

- Add the documentation.

May be we have also to think to the structure of this function ? Cumulative patch size distribution could be separated from power law fitting function ?

**Comment by fdschneider** [comment] 2015-07-06 13:23
yes. 
 I can take care of that one. 

the one we are going to work on is `fitpsd()`. This one takes an input from `psd()` which only provides the cumulative patch sizes from an input vector of patch sizes. There is no separate function yet providing that vector of patch sizes from a binary matrix. This depends on the labelling function `lbl()`.

**Comment by alaindanet** [comment] 2015-07-06 14:09
Okay, thank you Flo!

**Comment by fdschneider** [comment] 2015-07-07 16:14
I renamed the function into `indicator_fitpsd()` and this uses `indicator_cumpsd()` to generate a table of cumulative patch size distributions. the output object is of class `psdfit` with an own method for plot() and summary(). 

```r
data(B)
fit <- indicator_fitpsd(B)
plot(fit)
summary(fit)
```

I deleted the deprecated `patchsizedistr_ews.R`.

**Comment by fdschneider** [comment] 2015-07-07 16:26
I feel this needs some methodological discussion: 
@skefi @ssumithra @guttal @SabihaMajumder @MiguelBV 

Which candidate models for the cumulative patch size distribution function should be fitted here? So far, I implement: 

- a straight power law :  
   `log(p) ~ alpha *  log(size)`
- a truncated power law:  
   `log(p) ~ I( alpha*log(size)-size*Sx `
- an up-bent power law, assuming a single spanning cluster:   
  `log(p) ~  log(b) + log(1+(size^(alpha))/b )`

probably we also want an exponential function. Anything else? 

Also: how to pool data of different snapshots? I remember a discussion about eliminating the smallest or largest patches before fitting? Is there any such filtering you would like to apply?

**Comment by fdschneider** [comment] 2015-09-25 08:21
Presently, those models are compared by AIC, which is invalid since the data are very heterogeneous. For our grazing paper, we now iteratively fit a polynomial model on bootstrapped data to decide about the direction of the curvature, by looking at confidence intervals, and then fit the most appropriate model. This takes much more computation time.

Also, the exponent alpha is the exponent of the cumulative distribution. This should rather be made comparable to other studies by transforming to the exponent on non-cumulative data as described in White et al. 2008. 

Finally, we might want to have a switch that fits the models either to the cumulative distribution or the non-cumulative patch size distribution.

**Comment by MiguelBV** [comment] 2015-10-02 07:31
Hi there. I don't know what is the state of this right now. As you commented on the mail to Vishu you might have probs with the PSDs fitting I have a suggestion. In this web page you'll find an R function able to fit Patch size distributions: http://tuvalu.santafe.edu/~aaronc/powerlaws/. It is based on Clauset's paper.

This method uses maximum likelihood to fit patch size distributions and extracts alpha and xmin. As a suggestion regarding how to make distinctions between different functions, we can use the idea I was implementing for my paper: power law relative range. This is an indicator based on xmin, which says: from your data, which percentage of the sizes range are actually following a power law. Is a metric ranging from 0 (definitively not a PL) to 1 (all the range follows a PL). 

The technique is quite sensitive, although it might have problems to identificate truncated PLs. I think it might work fine as a general indicator of the proximity and deviation to/from PL-like functions of the patch size distribution. Tell me if interested and I'll explain it further.

**Comment by ssumithra** [comment] 2015-10-08 07:18
@fdschneider @MiguelBV 

What do you mean by heterogenous data? I think the ideal method is to fit and estimate the parameter values by MLE method followed by AIC-based model selection. I am unable to follow what the problem is with this? Could you please elaborate? Thanks!

**Comment by fdschneider** [comment] 2015-11-05 10:39
Thanks @MiguelBV and @ssumithra! 
Sorry for beeing silent on this for so long. Thats the major issue (the only issue) raised by the reviewers of our current paper. I think this still needs some discussion!  The Clauset method is also what was requested by our reviewer. 
 
A maximum-likelihood fit would be best, of course, but we do not have an appropriate MLE solution for truncated and particularly the up-bent power-law (limited by a large spanning cluster at the bottom). Also, even when fitting via max-likelihood the residuals on the model are heteroscedatic along the x-axis, i.e. the small patches are very well described but the large patches deviate more, which -- as far as I understood -- seems to invalidate a model comparison via AIC. 
This is why we compare the models by a method that is robust against heteroscedasticity (bootstrapping the significance of curvature in a polynomial model) and then fit phenomenological models (Powerlaw, truncated power-law, up-bent power-law) to obtain the exponent alpha. 

The thing is, the method you would apply depends on the question you want to address with your power-law analysis:

1. Can the data be described by a power-law, or do we have a truncation? 
2. Which fraction of the patches can be described by a power-law? (Miguels paper)
3. What is the exponent of the power-law beyond the truncation point (i.e. for larger patches)? 
4. Do we have significant spanning clusters? (My paper)
5. What is the exponent of the power-law below the truncation (i.e. for smaller patches) ? (my paper)
6. ...

It seems to me that this is related to the different kinds of criticality observed in the systems. 
- If expecting power-laws in 'healthy' systems, as in Turing patterns(, right?), with truncations indicating degradation, you will be asking 1,2 & 3. 
- If expecting spanning clusters in healthy systems, as in our grazing model, we would not expect a self-stabilising straight power-law at all. It's only a rare marginal case. Then the crossing of the power-law case might indicate the degradation or proximity to a critical threshold. Thus, questions 2, 4, and 5 make sense. 

The type of data defines which question you would be asking, right  (see @guttal's comment [here](https://github.com/fdschneider/spatial_warnings/issues/19#issuecomment-146586747))? When do we observe those two cases? What spatial feedbacks provide a transition between the two cases? Is there a generalizing theory for that? 

I could incorporate all of these metrics in one function, but maybe this does not make any sense or would be confusing. I will think about a flexible function that allows to customize the analysis. What is your preference here?

**Comment by alexgenin** [comment] 2016-10-10 13:12
Closing this discussion now: for fitting we follow Clauset's method for psd-fitting (MLE). 

Then there are two offered (high-level) indicator functions for patch-size distributions: 
 - patch-type: which distro is the best fit (tpl/pl/exp/lnorm) and how that varies along the gradient (+ when percolation occurs)
 - plrange: range over which the distribution behaves like a power-law (see Miguel's paper)

**Closed by alexgenin** 2016-10-10 13:12 UTC
Labels: enhancement, indicator function, not-technical, question
